language: cpp
os: linux
dist: xenial
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
      script:
      - make -j
      - ./main
    - compiler: clang
      script:
      - make -j
      - ./main
